In [48]:
import numpy as np
import tensorflow as tf
print(tf.__version__)
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))

2.20.0
Num GPUs Available: 0


#### Tensor Basics

In [17]:
# scalars 
x = tf.constant(5)
print("This is a scaler val: \t\t", x)

# vectors
x = tf.constant([1,2])
print("This is a vector of shape 1x2: \t", x)

# matrix
X = tf.constant([[1,2], [3,4]])
print("This is a matrix of shape 2x2: \n", X)

This is a scaler val: 		 tf.Tensor(5, shape=(), dtype=int32)
This is a vector of shape 1x2: 	 tf.Tensor([1 2], shape=(2,), dtype=int32)
This is a matrix of shape 2x2: 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [34]:
# check dimension
X = tf.constant([[1,2], [3,4]])
print(f"{X} has dimension of {X.ndim} with shape of {X.shape} \n-------------")

X = tf.constant([[[1,2], [3,4], [5,6]]])
print(f"{X} has dimension of {X.ndim} with shape of {X.shape} \n-------------")

X = tf.constant([[1,2], [3,4], [5,6]])
print(f"{X} has dimension of {X.ndim} with shape of {X.shape} \n-------------")

X = tf.constant([[1,2,3], [4, 5,6]])
print(f"{X} has dimension of {X.ndim} with shape of {X.shape} \n-------------")

X = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]], [[9,10], [11,12]]], dtype=tf.float16)
print(f"{X} has dimension of {X.ndim} with shape of {X.shape} \n-------------")

[[1 2]
 [3 4]] has dimension of 2 with shape of (2, 2) 
-------------
[[[1 2]
  [3 4]
  [5 6]]] has dimension of 3 with shape of (1, 3, 2) 
-------------
[[1 2]
 [3 4]
 [5 6]] has dimension of 2 with shape of (3, 2) 
-------------
[[1 2 3]
 [4 5 6]] has dimension of 2 with shape of (2, 3) 
-------------
[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]] has dimension of 3 with shape of (3, 2, 2) 
-------------


In [63]:
# we can specify the type of data inside our tensors
X = tf.constant([[1,2],[3,4]], dtype=tf.int16)
print(X.dtype)
print(f"{X} \n------------")

# we can also set object dtype
X = tf.constant(["apple", "cat", "car"])
print(f"{X} \n------------")
print(X.dtype)

# here tf is using immutable byte strings
x1 = X.numpy()[0]
print(f"{x1} is type {type(x1)}")
# convert it to string
x1_str = x1.decode("utf-8")
print(f"{x1_str} is type {type(x1_str)}")

<dtype: 'int16'>
[[1 2]
 [3 4]] 
------------
[b'apple' b'cat' b'car'] 
------------
<dtype: 'string'>
b'apple' is type <class 'bytes'>
apple is type <class 'str'>


In [ ]:
# we can have either mutable or immutable tensors
mutable_X = tf.Variable([1,2,3])
print(f"This is mutable tensor: {mutable_X}")
# we can update valsues in-place
mutable_X.assign([4,5,6])
print(f"This is new values: {mutable_X}\n-----------")

# this is immutable tensor
immutable_X = tf.constant([1,2,3])
print(f"This is immutable tensor: {immutable_X} \n-----------")
immutable_X[0] = 2 

This is mutable tensor: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
This is new values: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>
-----------
This is immutable tensor: [1 2 3] 
-----------


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

#### Create Tensors

**Ramdom Tensors**

In [ ]:
# random tensors

# set global level seed
tf.random.set_seed(42)

# or creates independent stateful generator with its own seed
X = tf.random.Generator.from_seed(42) # set seed

print("Generate from normal distribution: ", X.normal(shape=(2,2,2)), "\n----------")
print("Generate from uniform distribution: ", X.uniform(shape=(2,2,2)), "\n----------")

Gen from normal distribution:  tf.Tensor(
[[[-0.7565803  -0.06854702]
  [ 0.07595026 -1.2573844 ]]

 [[-0.23193763 -1.8107855 ]
  [ 0.09988727 -0.50998646]]], shape=(2, 2, 2), dtype=float32) 
----------
Gen from uniform distribution:  tf.Tensor(
[[[0.2674625  0.32031918]
  [0.4377985  0.57189393]]

 [[0.65885174 0.11768913]
  [0.11456561 0.19414282]]], shape=(2, 2, 2), dtype=float32) 
----------


In [158]:
# sort and shuffle

# shuffling (along the first dimension)
X = tf.constant([[1,2],[3,4],[5,6],[7,8]])
print(f"Dim: {X.shape}")
print(f"before: {X}")
X = tf.random.shuffle(X, seed=42)
print(f"after: {X}  \n--------------")

# to shuffle along the second dim, we need to transpose
X_shuffled_cols = tf.transpose(tf.random.shuffle(tf.transpose(X), seed=42)) # transpose, shuffle and re-transpose to original shape
print(X_shuffled_cols)


Dim: (4, 2)
before: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
after: [[1 2]
 [7 8]
 [3 4]
 [5 6]]  
--------------
tf.Tensor(
[[1 2]
 [7 8]
 [3 4]
 [5 6]], shape=(4, 2), dtype=int32)


**Special Tensors**

In [159]:
# create a tensor of ones with dim 5x3
tf.ones([5,3])

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [160]:
# create tensor of zeros with dim 3x6
tf.zeros([3,6])

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [161]:
# turn numpy arrays to tensors
numpy_A = np.arange(0,18, dtype=np.int32)
numpy_A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17], dtype=int32)

In [170]:
tf.constant(numpy_A)
tf.Variable(numpy_A)

# can define shape also
X = tf.constant(numpy_A, shape=(3,6))
print(X, "\n------------")

X = tf.constant(numpy_A, shape=(2,3,3))
print(X)

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]], shape=(3, 6), dtype=int32) 
------------
tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]], shape=(2, 3, 3), dtype=int32)


#### Tensor Attributes

> shape, rank, dimension, size

In [183]:
X = tf.constant(np.arange(0,120), shape=(2,3,4,5))

print(X)

tf.Tensor(
[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]], shape=(2, 3, 4, 5), dtype=int64)


In [184]:
print("shape: ", X.shape)
print("rank: ", X.ndim)
print("dimension: ", tf.rank(X))
print("size: ", tf.size(X))
print("size num: ", tf.size(x).numpy())
print("dtype: ", X.dtype)
print("elements along the last axis: ", X.shape[-1])

shape:  (2, 3, 4, 5)
rank:  4
dimension:  tf.Tensor(4, shape=(), dtype=int32)
size:  tf.Tensor(120, shape=(), dtype=int32)
size num:  2
dtype:  <dtype: 'int64'>
elements along the last axis:  5


**access dimensions**

In [180]:
print(X[1])
X[1].shape

tf.Tensor(
[[[ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]
  [ 75  76  77  78  79]]

 [[ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]], shape=(3, 4, 5), dtype=int64)


TensorShape([3, 4, 5])

In [182]:
print(X[0,1])
X[0,1].shape

tf.Tensor(
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]], shape=(4, 5), dtype=int64)


TensorShape([4, 5])

In [186]:
print(X[0,1,1])
X[0,1,1].shape

tf.Tensor([25 26 27 28 29], shape=(5,), dtype=int64)


TensorShape([5])