In [1]:
import numpy as np

import tensorflow as tf

import os
os.environ["TF_USE_LEGACY_KERAS"] = "1"  # Tell TF to use tf-keras
import tensorflow_probability as tfp

print(tf.__version__)
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))

2026-01-24 00:40:52.304653: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
2026-01-24 00:40:52.305043: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-24 00:40:52.343625: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-01-24 00:40:53.424079: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off,

2.20.0
Num GPUs Available: 0


2026-01-24 00:40:54.230378: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


#### Tensor Basics

In [2]:
# scalars 
x = tf.constant(5)
print("This is a scaler val: \t\t", x)

# vectors
x = tf.constant([1,2])
print("This is a vector of shape 1x2: \t", x)

# matrix
X = tf.constant([[1,2], [3,4]])
print("This is a matrix of shape 2x2: \n", X)

This is a scaler val: 		 tf.Tensor(5, shape=(), dtype=int32)
This is a vector of shape 1x2: 	 tf.Tensor([1 2], shape=(2,), dtype=int32)
This is a matrix of shape 2x2: 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [3]:
# check dimension
X = tf.constant([[1,2], [3,4]])
print(f"{X} has dimension of {X.ndim} with shape of {X.shape} \n-------------")

X = tf.constant([[[1,2], [3,4], [5,6]]])
print(f"{X} has dimension of {X.ndim} with shape of {X.shape} \n-------------")

X = tf.constant([[1,2], [3,4], [5,6]])
print(f"{X} has dimension of {X.ndim} with shape of {X.shape} \n-------------")

X = tf.constant([[1,2,3], [4, 5,6]])
print(f"{X} has dimension of {X.ndim} with shape of {X.shape} \n-------------")

X = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]], [[9,10], [11,12]]], dtype=tf.float16)
print(f"{X} has dimension of {X.ndim} with shape of {X.shape} \n-------------")

[[1 2]
 [3 4]] has dimension of 2 with shape of (2, 2) 
-------------
[[[1 2]
  [3 4]
  [5 6]]] has dimension of 3 with shape of (1, 3, 2) 
-------------
[[1 2]
 [3 4]
 [5 6]] has dimension of 2 with shape of (3, 2) 
-------------
[[1 2 3]
 [4 5 6]] has dimension of 2 with shape of (2, 3) 
-------------
[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]] has dimension of 3 with shape of (3, 2, 2) 
-------------


2026-01-24 00:40:54.293967: E tensorflow/core/util/util.cc:131] oneDNN supports DT_HALF only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


In [4]:
# we can specify the type of data inside our tensors
X = tf.constant([[1,2],[3,4]], dtype=tf.int16)
print(X.dtype)
print(f"{X} \n------------")

# we can also set object dtype
X = tf.constant(["apple", "cat", "car"])
print(f"{X} \n------------")
print(X.dtype)

# here tf is using immutable byte strings
x1 = X.numpy()[0]
print(f"{x1} is type {type(x1)}")
# convert it to string
x1_str = x1.decode("utf-8")
print(f"{x1_str} is type {type(x1_str)}")

<dtype: 'int16'>
[[1 2]
 [3 4]] 
------------
[b'apple' b'cat' b'car'] 
------------
<dtype: 'string'>
b'apple' is type <class 'bytes'>
apple is type <class 'str'>


In [5]:
# we can cast data types on tensors
X = tf.constant([1,2,3,4])
print(f"{X} with dtype of {X.dtype}")

X = tf.cast(X, dtype=tf.float16)
print(f"{X} with dtype of {X.dtype}")

[1 2 3 4] with dtype of <dtype: 'int32'>
[1. 2. 3. 4.] with dtype of <dtype: 'float16'>


In [6]:
# we can have either mutable or immutable tensors
mutable_X = tf.Variable([1,2,3])
print(f"This is mutable tensor: {mutable_X}")
# we can update valsues in-place
mutable_X.assign([4,5,6])
print(f"This is new values: {mutable_X}\n-----------")

# this is immutable tensor
try:
    immutable_X = tf.constant([1,2,3])
    print(f"This is immutable tensor: {immutable_X} \n-----------")
    immutable_X[0] = 2
except Exception as error:
    print(type(error).__name__, ":", error)

This is mutable tensor: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
This is new values: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>
-----------
This is immutable tensor: [1 2 3] 
-----------
TypeError : 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment


#### Create Tensors

**Ramdom Tensors**

In [7]:
# random tensors

# set global level seed
tf.random.set_seed(42)

# or creates independent stateful generator with its own seed
X = tf.random.Generator.from_seed(42) # set seed

print("Generate from normal distribution: ", X.normal(shape=(2,2,2)), "\n----------")
print("Generate from uniform distribution: ", X.uniform(shape=(2,2,2)), "\n----------")

Generate from normal distribution:  tf.Tensor(
[[[-0.7565803  -0.06854702]
  [ 0.07595026 -1.2573844 ]]

 [[-0.23193763 -1.8107855 ]
  [ 0.09988727 -0.50998646]]], shape=(2, 2, 2), dtype=float32) 
----------
Generate from uniform distribution:  tf.Tensor(
[[[0.2674625  0.32031918]
  [0.4377985  0.57189393]]

 [[0.65885174 0.11768913]
  [0.11456561 0.19414282]]], shape=(2, 2, 2), dtype=float32) 
----------


In [8]:
# sort and shuffle

# shuffling (along the first dimension)
X = tf.constant([[1,2],[3,4],[5,6],[7,8]])
print(f"Dim: {X.shape}")
print(f"before: {X}")
X = tf.random.shuffle(X, seed=42)
print(f"after: {X}  \n--------------")

# to shuffle along the second dim, we need to transpose
X_shuffled_cols = tf.transpose(tf.random.shuffle(tf.transpose(X), seed=42)) # transpose, shuffle and re-transpose to original shape
print(X_shuffled_cols)


Dim: (4, 2)
before: [[1 2]
 [3 4]
 [5 6]
 [7 8]]
after: [[3 4]
 [5 6]
 [1 2]
 [7 8]]  
--------------
tf.Tensor(
[[3 4]
 [5 6]
 [1 2]
 [7 8]], shape=(4, 2), dtype=int32)


**Special Tensors**

In [9]:
# create a tensor of ones with dim 5x3
tf.ones([5,3])

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [10]:
# create tensor of zeros with dim 3x6
tf.zeros([3,6])

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [11]:
# turn numpy arrays to tensors
numpy_A = np.arange(0,18, dtype=np.int32)
numpy_A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17], dtype=int32)

In [12]:
tf.constant(numpy_A)
tf.Variable(numpy_A)

# can define shape also
X = tf.constant(numpy_A, shape=(3,6))
print(X, "\n------------")

X = tf.constant(numpy_A, shape=(2,3,3))
print(X)

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]], shape=(3, 6), dtype=int32) 
------------
tf.Tensor(
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]], shape=(2, 3, 3), dtype=int32)


#### Tensor Attributes

> shape, rank, dimension, size

In [13]:
X = tf.constant(np.arange(0,120), shape=(2,3,4,5))

print(X)

tf.Tensor(
[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]], shape=(2, 3, 4, 5), dtype=int64)


In [14]:
print("shape: ", X.shape)
print("rank: ", X.ndim)
print("dimension: ", tf.rank(X))
print("size: ", tf.size(X))
print("size num: ", tf.size(x).numpy())
print("dtype: ", X.dtype)
print("elements along the last axis: ", X.shape[-1])

shape:  (2, 3, 4, 5)
rank:  4
dimension:  tf.Tensor(4, shape=(), dtype=int32)
size:  tf.Tensor(120, shape=(), dtype=int32)
size num:  2
dtype:  <dtype: 'int64'>
elements along the last axis:  5


**access dimensions**

In [15]:
print(X[1])
X[1].shape

tf.Tensor(
[[[ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]
  [ 75  76  77  78  79]]

 [[ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]], shape=(3, 4, 5), dtype=int64)


TensorShape([3, 4, 5])

In [16]:
print(X[0,1])
X[0,1].shape

tf.Tensor(
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]], shape=(4, 5), dtype=int64)


TensorShape([4, 5])

In [17]:
print(X[0,1,1])
X[0,1,1].shape

tf.Tensor([25 26 27 28 29], shape=(5,), dtype=int64)


TensorShape([5])

#### Tensor Operations

##### Arithmetic Operations

In [18]:
X = tf.ones(shape=(1,5))
print(f"Original Tensor: {X}, with shape {X.shape} \n--------------")

# scalar addition
X = X+10
print(f"Added 10 : {X} \n--------------")
# using tensorflow's built-in funcs will help leverage GPU to accelearate opeartaions
X = tf.add(X,10)
print(f"Added 10 : {X} \n--------------")
# same goes for tf.multiply, tf.divide, tf.subtract

# elementwise multiplication
X = tf.constant([1,2,3,4], shape=(1,4))
tf.multiply(X, X)


Original Tensor: [[1. 1. 1. 1. 1.]], with shape (1, 5) 
--------------
Added 10 : [[11. 11. 11. 11. 11.]] 
--------------
Added 10 : [[21. 21. 21. 21. 21.]] 
--------------


<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 1,  4,  9, 16]], dtype=int32)>

##### Broadcasting

Broadcasting is TensorFlow’s way of performing element‑wise operations on tensors with different shapes as long as their shapes are compatible, meaning TensorFlow can “stretch” dimensions of size 1 so that two tensors can align for arithmetic operations. Broadcasting allows writing vectorized code without manually repeating or reshaping tensors.

**Broadcasting Rules**: Two dimensions are compatible when
- They are equal, or
- One of them is 1 
<br>

TensorFlow compares shapes from right to left (trailing dimensions first).
If all dimensions are compatible, TensorFlow automatically broadcasts the smaller tensor.

check more on broadcasting operations here https://numpy.org/doc/stable/user/basics.broadcasting.html


In [19]:
# broadcasting with scalars
X = tf.constant([1., 2., 3.])
y = 2.0
print(f"{X} with shape {X.shape}")
print(f"scalar {y}")
print("X * y gives us: ", X * y)
print("y is broadcasted to shape internally (3,) → [2., 2., 2.]")

[1. 2. 3.] with shape (3,)
scalar 2.0
X * y gives us:  tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)
y is broadcasted to shape internally (3,) → [2., 2., 2.]


In [20]:
# broadcasting a 1D tensor to a 2D tensor
X = tf.constant([
    [0., 0., 0.],
    [10., 10., 10.],
    [20., 20., 20.],
    [30., 30., 30.]
])  # shape (4, 3)
b = tf.constant([1., 2., 3.])  # shape (3,)
print("X + b =\n", X + b)
print("----------------")
print(
'''
X shape: (4, 3)
b original shape: (3,) → treated as (1, 3)
b is broadcast across rows → result shape (4, 3)
'''
)

X + b =
 tf.Tensor(
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]], shape=(4, 3), dtype=float32)
----------------

X shape: (4, 3)
b original shape: (3,) → treated as (1, 3)
b is broadcast across rows → result shape (4, 3)



In [21]:
# broadcasting with inserted dimensions
a = tf.constant([0., 10., 20., 30.])  # shape (4,)
b = tf.constant([1., 2., 3.])         # shape (3,)
a_expanded = a[:, tf.newaxis] # Make a into shape (4, 1)
print("a_expanded shape:", a_expanded.shape)
print("b shape:", b.shape)

result = a_expanded + b
print("Result shape:", result.shape)
print(result)
print(
'''
a[:, None] → shape (4, 1)
b → shape (3,) → treated as (1, 3)
Result → (4, 3) outer addition
'''
)

a_expanded shape: (4, 1)
b shape: (3,)
Result shape: (4, 3)
tf.Tensor(
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]], shape=(4, 3), dtype=float32)

a[:, None] → shape (4, 1)
b → shape (3,) → treated as (1, 3)
Result → (4, 3) outer addition



In [22]:
# broadcasting a 3D tensor with a 1D tensor
X = tf.random.uniform((4, 3, 2))  # shape (4, 3, 2)
b = tf.constant([1., 2.])         # shape (2,)
print("X shape:", X.shape)
print("b shape:", b.shape)
Y = X + b
print("Y shape:", Y.shape)
print(
'''
X last dimension = 2
b shape = (2,) → aligns with last dimension
b is broadcast across the first two axes → (4, 3, 2)
'''
)

X shape: (4, 3, 2)
b shape: (2,)
Y shape: (4, 3, 2)

X last dimension = 2
b shape = (2,) → aligns with last dimension
b is broadcast across the first two axes → (4, 3, 2)



In [23]:
# broadcasting fails when trailing dimensions don’t match and neither is 1.
a = tf.constant([1., 2., 3.])   # shape (3,)
b = tf.constant([1., 2., 3., 4.])  # shape (4,)
try:
    print(a + b)
except Exception as e:
    print("Broadcasting error:", e)

Broadcasting error: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3] vs. [4] [Op:AddV2] name: 


2026-01-24 00:40:54.680332: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INVALID_ARGUMENT: Incompatible shapes: [3] vs. [4]


##### Dimension Expension

In [24]:
# adding dimension to tensor
np_X = np.arange(0,10, dtype=np.int32) 
X = tf.constant(np_X, shape=(1,10))
print(f"Original Tensor: {X}, with shape {X.shape} \n--------------")

# added new axis at the end
X = tf.constant(np_X, shape=(1,10))
X = X[..., tf.newaxis]
print(f"New tensor with shape {X.shape} \n------------")

# added new axis in the middle
X = tf.constant(np_X, shape=(5,2))
X = X[:,tf.newaxis,:]
print(f"New tensor with shape {X.shape} \n------------")

# 0 to expand first axis, 1 for second,...-1 to expand the final axis
np_X = np.arange(0,24, dtype=np.int32) 
X = tf.constant(np_X, shape=(4,3,2))
print(f"Original Tensor with shape {X.shape} \n--------------")
X = tf.expand_dims(X, axis=-1) 
print(f"New tensor with shape {X.shape}")

Original Tensor: [[0 1 2 3 4 5 6 7 8 9]], with shape (1, 10) 
--------------
New tensor with shape (1, 10, 1) 
------------
New tensor with shape (5, 1, 2) 
------------
Original Tensor with shape (4, 3, 2) 
--------------
New tensor with shape (4, 3, 2, 1)


##### Matrix Multiplication

In [25]:
A = tf.constant([[1, 1],
                 [2, 2],
                 [3, 3]])   # shape (3, 2)
B = tf.constant([[0, 0],
                 [1, 0],
                 [0, 1]])   # shape (3, 2)
print("A shape:", A.shape)
print("B shape:", B.shape)
print("\nElement-wise multiply:\n", A * B)
print("Both tensors have same shape (3, 2) → element‑wise operations are valid.")

A shape: (3, 2)
B shape: (3, 2)

Element-wise multiply:
 tf.Tensor(
[[0 0]
 [2 0]
 [0 3]], shape=(3, 2), dtype=int32)
Both tensors have same shape (3, 2) → element‑wise operations are valid.


In [26]:
# but matrix multiplication matmul is different
try:
    tf.matmul(A, B)
except Exception as error:
    print(type(error).__name__, ":", error)


InvalidArgumentError : {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 


2026-01-24 00:40:54.736290: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INVALID_ARGUMENT: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2]


**A** is **3 × 2** and **B** is **3 × 2**

**Matrix multiplication rule:**
> (**m × n**) · (**p × q**) is valid only if **n = p**
**Here:**
- **A** inner dimension = **2**
- **B** inner dimension = **3**

Since **2 ≠ 3**, TensorFlow raises an error.


In [27]:
# fix the above using transpose
B_T = tf.transpose(B)   # shape becomes (2, 3)
print(f"transposed from \n {B} \n to \n {B_T}" )
print("B_T shape:", B_T.shape)

result = tf.matmul(A, B_T)
print("\nA @ B_T =\n", result)

transposed from 
 [[0 0]
 [1 0]
 [0 1]] 
 to 
 [[0 1 0]
 [0 0 1]]
B_T shape: (2, 3)

A @ B_T =
 tf.Tensor(
[[0 1 1]
 [0 2 2]
 [0 3 3]], shape=(3, 3), dtype=int32)


In [28]:
# or we can reshape but result will be different (we get same shape but order of elements is different now)
B_reshaped = tf.reshape(B, (2, 3))
print(f"reshaped from \n {B} \n to \n {B_reshaped}")

result = tf.matmul(A, B_reshaped)
print("\nA @ B_T =\n", result)

reshaped from 
 [[0 0]
 [1 0]
 [0 1]] 
 to 
 [[0 0 1]
 [0 0 1]]

A @ B_T =
 tf.Tensor(
[[0 0 2]
 [0 0 4]
 [0 0 6]], shape=(3, 3), dtype=int32)


Transpose rotates axes but Reshape only rearranges elements in memory. They are NOT interchangeable.

**TensorDot Operations**

**`tf.tensordot`** performs **tensor contraction**, which is a generalized form of the dot product and matrix multiplication.
It allows us to specify which **axes to contract over**, making it more flexible than **`tf.matmul`**.

**Tensor contraction means:**

- Multiply elements along shared axes  
- Then sum over those axes  
- Resulting tensor has reduced rank  

**It generalizes:**

- **Dot product** → Contract over **1 axis**
- **Matrix multiplication** → Contract over **last axis of A** and **second-last axis of B**
- **Higher-order tensor operations** → Contract over **multiple axes**


In [29]:
# outer product
a = tf.constant([1, 2, 3])   # shape (3,)
b = tf.constant([4, 5])      # shape (2,)
outer = tf.tensordot(a, b, axes=0)
print(outer)
print("Shape:", outer.shape)

tf.Tensor(
[[ 4  5]
 [ 8 10]
 [12 15]], shape=(3, 2), dtype=int32)
Shape: (3, 2)


No contraction  

**Result shape → (3, 2)**  
Equivalent to **outer product**


In [30]:
# basic dot product
a = tf.constant([1, 2, 3])   # shape (3,)
b = tf.constant([4, 5, 6])   # shape (3,)
result = tf.tensordot(a, b, axes=1)
print(result)

tf.Tensor(32, shape=(), dtype=int32)


**Contract over 1 axis → standard dot product:**  
1 × 4 + 2 × 5 + 3 × 6 = **32**


In [31]:
# matrix multiplication
A = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])   # shape (3, 2)
B = tf.constant([[10, 20, 30],
                 [40, 50, 60]])  # shape (2, 3)
result = tf.tensordot(A, B, axes=[[1], [0]])
print(result)

tf.Tensor(
[[ 90 120 150]
 [190 260 330]
 [290 400 510]], shape=(3, 3), dtype=int32)


**A axis 1** (size **2**)  
**B axis 0** (size **2**)  
**Result shape → (3, 3)** which is same as **`tf.matmul(A, B)`**

In [32]:
# contracting over multiple axes
A = tf.random.uniform((2, 3, 4))  # shape (2, 3, 4)
B = tf.random.uniform((3, 4, 5))  # shape (3, 4, 5)
# Contract over axes (1,2) of A and (0,1) of B
result = tf.tensordot(A, B, axes=[[1, 2], [0, 1]])
print("Result shape:", result.shape)

Result shape: (2, 5)


**A axes:** (3, 4)  
**B axes:** (3, 4)  

Contracting removes those axes

**Remaining dims:**

- **A leftover:** (2,)
- **B leftover:** (5,)

**Result shape → (2, 5)**

This is impossible with **`tf.matmul`**, but we can do with **`tensordot`**.


#### Tensor Aggregations

In [33]:
# get absolute vals
X = tf.constant([-9,-9, 7, 8.6])
print(f"abs val: {tf.abs(X)}")

# finx min max
X = tf.constant(np.random.randint(0, 100, 50))
print(f"min: {tf.reduce_min(X)}")
print(f"max: {tf.reduce_max(X)}")
print(f"mean: {tf.reduce_mean(X)}")
print(f"sum: {tf.reduce_sum(X)}")

print(f"variance: {tfp.stats.variance(X)}")

X = tf.cast(X, dtype=tf.float32)
print(f"std_dev: {tfp.stats.stddev(X)}") # this only works with real or complex nums

# or we can use tf.math instead of tfp module
print(tf.math.reduce_std(tf.cast(X, dtype=tf.float32)))
tf.math.reduce_variance(tf.cast(X, dtype=tf.float32))

abs val: [9.  9.  7.  8.6]
min: 0
max: 89
mean: 43
sum: 2164
variance: 719
std_dev: 26.825389862060547
tf.Tensor(26.82539, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=719.6015625>

in above operations since X is 1‑D, the reduction collapses the entire tensor to a scalar.

**What Does “Reduce” Mean?**

A **reduction operation**:

- Takes a tensor with **N dimensions**
- Aggregates values along a **specified axis**
- Returns a tensor with **fewer dimensions**

This is different from “normal” math function


In [34]:
X = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])
print("X shape:", X.shape)

print(f"reduce over all elements: {tf.reduce_sum(X)}")
print(f"reduce over axis 0 (col-wise): {tf.reduce_sum(X, axis=0)}")
print(f"reduce over axis 1 (row-wise): {tf.reduce_sum(X, axis=1)}")

X shape: (2, 3)
reduce over all elements: 21
reduce over axis 0 (col-wise): [5 7 9]
reduce over axis 1 (row-wise): [ 6 15]


Axis 0
- **Column 1:** 1 + 4
- **Column 2:** 2 + 5  
- **Column 3:** 3 + 6

Axis 1
- **Row 1:** 1 + 2 + 3  
- **Row 2:** 4 + 5 + 6